### ISSUE TITLE
Update IPCC on phone

### ISSUE THREAD

**Issue by iman432** [mrlnc/ipcc-downloader#1]
Hi,
Thank you for this job, after modifying IPCC there is a way for updating IPCC on phone? like iTunes or ...

**Comment by whatyoubendoing** [comment]
After downloading you can install the in 2 ways.

### Option 1: Is to install via ideviceinstaller 

```
brew install ideviceinstaller 
deviceinstaller -i Hutchison_uk_iPhone.ipcc
```

### Option 2: Is to install via Finder

Enable carrier testing via the terminal 
```
defaults write com.apple.AMPDevicesAgent carrier-testing -bool YES
```
Plug in your iPhone. Open finder and  Opt  + Click  on “Check For Update“. Select the ipcc file, it should take 2 seconds to install, reboot the iPhone and voila’ updated carrier settings.

**Comment by iman432** [comment]
Thanks a lot
