### ISSUE TITLE
Modifying IPCC file and regenerate signature

### ISSUE THREAD

**Issue by iman432** [mrlnc/ipcc-downloader#2]
Hi,

There is a way for modifying plist files in IPCC and regenerate signature for them? as after modifying, without signature it cannot work on phone.

Thank you for your time.

**Comment by mrlnc** [comment]
I'm afraid that's what the signatures are for: they prevent modifications. I've read that jailbroken phones may not have that limitation, but I cannot help further there. This is just my little downloader script :)
